//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngresoPersonal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotocheckTest
    {
        public int Cod_Per { get; set; }
        public string Cod_Tarjeta { get; set; }
        public string Cod_Trabajador { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Domicilio { get; set; }
        public string DNI { get; set; }
        public Nullable<short> Activo { get; set; }
        public string Fotos { get; set; }
        public string Cod_Tarjeta2 { get; set; }
        public string cod_Fotocheck { get; set; }
        public string GrupoSanguineo { get; set; }
        public string alergias { get; set; }
        public string Cargo { get; set; }
        public int id { get; set; }
    }
}
